### PR TITLE
Implement some tests

### PR DESCRIPTION
**Pull request by oliverpool**
I implemented some tests (more as an exercise, as a real interest)

### CODE REVIEW

**Comment by mattn** [comment]
Do you have reason that you implement ProxyConf as non-pointer?

**Comment by oliverpool** [comment]
Not really.

Maybe to prevent it being modified by one of the callers? (resulting in a wrong value to future callers)

**Comment by mattn** [comment]
Thanks. Could you please change the struct to pointers?

**Comment by oliverpool** [comment]
> Could you please change the struct to pointers?

Sure, which ones ? (you can comment on the [files](https://github.com/mattn/go-ieproxy/pull/3/files) tab with the `+` button near the concerned lines)

**Comment by mattn** [comment]
Ah, wait. It's right.

**Comment by mattn** [comment]
I wonder that user may want to modify(add) NoProxy on runtime. How do you think?

**Comment by oliverpool** [comment]
I think they should directly call `os.SetEnv('no_proxy', ...)` in their `init()` function

**Comment by mattn** [comment]
If implement oauth client using browser, we will spawn local http server, and open browser like below.

```go
l, _ := net.Listen("tcp", ":0") // random port
go http.Serve(l)
// possible to change NoProxy?
browserOpen("http://" + l.Addr().String())
```

**Comment by mattn** [comment]
Ah, sorry. I was confused. It's a case using browser not http.Client. Could you take me time to think usecase?

**Comment by oliverpool** [comment]
If your server is local, it will be bypassed: https://golang.org/src/net/http/transport.go?s=9224:9281#L237

```
// useProxy reports whether requests to addr should use a proxy,
  1084	// according to the NO_PROXY or no_proxy environment variable.
  1085	// addr is always a canonicalAddr with a host and port.
  1086	func useProxy(addr string) bool {
  1087		if len(addr) == 0 {
  1088			return true
  1089		}
  1090		host, _, err := net.SplitHostPort(addr)
  1091		if err != nil {
  1092			return false
  1093		}
  1094		if host == "localhost" {
  1095			return false
  1096		}
  1097		if ip := net.ParseIP(host); ip != nil {
  1098			if ip.IsLoopback() {
  1099				return false
  1100			}
  1101		}
```

**Comment by mattn** [comment]
Yes, it call `httpProxyEnv.Get()` for each call of ProxyFromEnvironment. Seems good to me.

**Comment by mattn** [comment]
Good. Thanks!

**Pull request merged**
