### PR TITLE
fix: added !cgo build contraint

### LINKED ISSUE #34: build fails on darwin
Describe the bug
Building things that use this library seems to yield an error on darwin, both amd64 and arm64.

Example output:

❯ GOOS=darwin GOARCH=arm64 go build .
# github.com/mattn/go-ieproxy
../../Go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:36:9: undefined: getConf
../../Go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:41:9: undefined: reloadConf
../../Go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
../../Go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:53:13: psc.findProxyForURL undefined (type *Proxy

### PR DESCRIPTION
**Pull request by caarlos0**
closes #34

should probably merge #37 too

### CODE REVIEW

**Comment by mattn** [comment]
Thanks. Could you please rebase master branch?

**Comment by caarlos0** [comment]
@mattn sure, done!

**Comment by bdebyl** [comment]
Would love to get this merged to fix darwin builds -- @mattn when you have time :)

**Comment by chrislusf** [comment]
Ping

Eagerly waiting for this!

**Comment by mattn** [comment]
Sorry my delay. Will merge soon.

**Comment by mattn** [comment]
Hmm.
image

**Comment by caarlos0** [comment]
let me rebase it with master, 1min

**Comment by caarlos0** [comment]
@mattn done

**Comment by mattn** [comment]
Thanks all.

**Pull request merged**
