### PR TITLE
Fall through automatic proxy detection if it returns no URL.

### LINKED ISSUE #11: Wrong order of priority of Automatic over Static config on Windows.
In `proxyMiddleman()` in `proxyMiddleman_windows.go`, the automatic config is used if it is enabled, even if static config is enabled as well. However, all common Windows software ~~appears to prioritize static config over automatic config when it is enabled~~ still considers static config if automatic config does not deliver any proxy, most notably the major browsers including Internet Explorer itself.

### PR DESCRIPTION
**Pull request by MMulthaupt**
Fixes #11.

### CODE REVIEW

**Comment by mattn** [comment]
@adreed-msft Is this you want?

**Comment by dragetd** [comment]
It is also aligned with the way the usual priority is. So I think this should be merged, no matter if @adreed-msft wants this or not. ;-)

**Comment by adreed-msft** [comment]
^

This seems like a smallish change. I'll take a look into what it entails and drop a code review when I get into the office.

**Comment by adreed-msft** [comment]
:shipit:

**Comment by mattn** [comment]
Thank you

**Pull request merged**
