### PR TITLE
Additional checks were added to toggle between the registry key LOCAL…

### PR DESCRIPTION
**Pull request by KedarB**
…_MACHINE and CURRENT_USER

Following are the reasons to change the previous logic.
1> In Windows Service, if the program tries to access the CURRENT_USER, it is automatically diverted to HKEY_USERS\.DEFAULT. This results in a success and hence there is no error.
2> To avoid above issue, we no check the registry value 'ProxySettingsPerUser', which will help to decide which registry needs to be accessed. If the value of ProxySettingsPerUser is '1', it means it should use CURRENT_USER and if it is '0', it should use LOCAL_MACHINE.

### CODE REVIEW

**Comment by mattn** [comment]
@JohnRusk Don't this break your use-case?

**Comment by JohnRusk** [comment]
> @JohnRusk Don't this break your use-case?

It seems OK to me, because the code only uses the registry settings if the earlier API-based lookups don't return anything.

But maybe I'm missing something.  Is there are specific reason why you thought it would break our use case?

**Comment by mattn** [comment]
Sorry. I just worried about I might break something for your use-case.

**Comment by mattn** [comment]
Thanks.

**Pull request merged**
